### ISSUE TITLE
No Full screen

### ISSUE THREAD

**Issue by harmloh** [MaartenBaert/ssr#589]
![screenshot from 2017-11-25 16-06-55](https://user-images.githubusercontent.com/33976835/33228633-b0af3730-d1fa-11e7-99c8-85dc423ece29.png)

i can't get full screen and can't do setting also, 
i don't know hot to fix this, i am using Fedora 27

**Comment by trebmuh** [comment]
With MATE as a desktop environment, I can Alt + click on the windows to move it.
You probably can use the TAB key (press 3 times) on your keyboard as well which will "click" on the "continue" button that we can't see because hided on your screenshot.

**Comment by harmloh** [comment]
I did , can’t work , i can’t see the option , and i guess the option is on the bottom , and i click everywhere on the bottom , i could get setting but can’t get all options on there , it seems the app not fit on my screen Fedora 27 

You can see what i did on this video, the link video is on here —> https://app.box.com/s/ifqiai093y680qi5bxg57jgehk74uxrt

I move my cursor scroll to up , but cant see the option :(

**Comment by MaartenBaert** [comment]
Your screen resolution is too low. This is fixed in the latest SSR from master, but it hasn't been released yet. You can compile it from source if you want.

**Comment by harmloh** [comment]
What source ? Can you tell me , i still dont understand 

My laptop is allienware MX11 r3 
I think this screen big enough but i dont mnow why the simple screen recorder not fit on my screen

**Comment by MaartenBaert** [comment]
Your screen resolution is 1366x768, which is small by modern standards. If you don't know how to compile from source, you will have to wait until the next update, sorry.
