### ISSUE TITLE
ssr-glinject doesn't work without stdout.

### ISSUE THREAD

**Issue by CobaltSpace** [MaartenBaert/ssr#856]
In steam, `ssr-glinject %command%` sometimes crashes and the game doesn't appear to even launch.

When I run `ssr-glinject %command% > /dev/null`, it works fine.

When I run `ssr-glinject %command% 2> logfile` to get what stderr is, `logfile` contains:
```
/usr/bin/ssr-glinject: line 62: echo: write error: Input/output error
```
I am on Arch Linux.

Output of `simplescreenrecorder --version`:
```
SimpleScreenRecorder 0.4.3
Compiled with GCC 10.2.0
Qt: header 5.15.2, lib 5.15.2
libavformat: header 58.45.100, lib 58.45.100
libavcodec: header 58.91.100, lib 58.91.100
libavutil: header 56.51.100, lib 56.51.100
libswscale: header 5.7.100, lib 5.7.100
```

**Comment by MaartenBaert** [comment]
I think it should be fixed now, can you try again?

**Comment by CobaltSpace** [comment]
`ssr-glinject %command%` still crashes, `ssr-glinject %command% > somefile` crashes, and `ssr-glinject %command% 2> somefile` works fine (`somefile` can be `/dev/null`).

It works without stdout, but now needs stderr.

After looking into it more, I think the issue is the `set -e` at the top.  Fixes include adding `set +e` above the echo commands, adding `|| true` to the end of the echo commands, or removing `set -e` if the only thing that can possibly fail in the script is echo commands.

**Comment by MaartenBaert** [comment]
I don't like disabling error checking in general, so I've added ` || true` to the two echo lines that print unconditionally. The other lines involve actual error messages from the script or help text explicitly requested by the user, so if those can't be printed it seems better to treat that as an error.
